// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231019115027_BookRating")]
    partial class BookRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn_10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61e8c388-4d08-454b-8dcc-ff25c6eec0ad"),
                            Author = "F. Scott Fitzgerald",
                            Description = "The Great Gatsby is a 1925 ",
                            Isbn_10 = "0743273567",
                            Isbn_13 = "9780743273565",
                            Rating = 5,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("67cf139f-3c77-42c3-aaf7-a87da9b2e085"),
                            Author = "Charles Dickens",
                            Description = "Book",
                            Isbn_10 = "1293585899",
                            Isbn_13 = "2958373967392",
                            Rating = 4,
                            Title = "Moby Dick"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
